name: CI/CD Pipeline

# 1. Налаштування тригерів (подій, що запускають процес)
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    #1. Вказуємо середовище для виконання Linux
    runs-on: ubuntu-latest

    steps:
    # Крок для отримання коду з репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Налаштування Node.js (версія 20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Пришвидшує наступні запуски

      # 3. Встановлення залежностей (Clean Install)
      - name: Install dependencies
        run: npm ci

      # 4. Перевірка якості коду (Linting)
      - name: Run Lint
        run: npm run lint

      # 5. Запуск тестів
      - name: Run Tests
        run: npm run test
        env:
          # Ми беремо секрет із "сейфа" GitHub і даємо йому ім'я для тестів
          MY_API_KEY: ${{ secrets.MY_PROJECT_API_KEY }}